/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminCatalogosRouteImport } from './routes/admin/catalogos'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AnaliticaIndexRouteImport } from './routes/analitica/index'
import { Route as AnaliticaCarga147RouteImport } from './routes/analitica/carga-147'
import { Route as AnaliticaMapaRouteImport } from './routes/analitica/mapa'
import { Route as CasosIndexRouteImport } from './routes/casos/index'
import { Route as CasosTrackingNumberRouteImport } from './routes/casos/$trackingNumber'
import { Route as CasosNuevoRouteImport } from './routes/casos/nuevo'
import { Route as RecepcionIndexRouteImport } from './routes/recepcion/index'
import { Route as RecepcionLlamadasRouteImport } from './routes/recepcion/llamadas'
import { Route as ReportesIndexRouteImport } from './routes/reportes/index'
import { Route as ReportesReportIdRouteImport } from './routes/reportes/$reportId'
import { Route as ReportesNuevoRouteImport } from './routes/reportes/nuevo'
import { Route as ReportesRevisionIndexRouteImport } from './routes/reportes/revision/index'
import { Route as ReportesRevisionEmailIngestionIdRouteImport } from './routes/reportes/revision/$emailIngestionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogosRoute = AdminCatalogosRouteImport.update({
  id: '/admin/catalogos',
  path: '/admin/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaIndexRoute = AnaliticaIndexRouteImport.update({
  id: '/analitica/',
  path: '/analitica/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaCarga147Route = AnaliticaCarga147RouteImport.update({
  id: '/analitica/carga-147',
  path: '/analitica/carga-147',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaMapaRoute = AnaliticaMapaRouteImport.update({
  id: '/analitica/mapa',
  path: '/analitica/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosTrackingNumberRoute = CasosTrackingNumberRouteImport.update({
  id: '/casos/$trackingNumber',
  path: '/casos/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosNuevoRoute = CasosNuevoRouteImport.update({
  id: '/casos/nuevo',
  path: '/casos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionIndexRoute = RecepcionIndexRouteImport.update({
  id: '/recepcion/',
  path: '/recepcion/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionLlamadasRoute = RecepcionLlamadasRouteImport.update({
  id: '/recepcion/llamadas',
  path: '/recepcion/llamadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIndexRoute = ReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesReportIdRoute = ReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesNuevoRoute = ReportesNuevoRouteImport.update({
  id: '/reportes/nuevo',
  path: '/reportes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRevisionIndexRoute = ReportesRevisionIndexRouteImport.update({
  id: '/reportes/revision/',
  path: '/reportes/revision/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRevisionEmailIngestionIdRoute =
  ReportesRevisionEmailIngestionIdRouteImport.update({
    id: '/reportes/revision/$emailIngestionId',
    path: '/reportes/revision/$emailIngestionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/analitica/': typeof AnaliticaIndexRoute
  '/casos/': typeof CasosIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/reportes/revision/': typeof ReportesRevisionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/analitica': typeof AnaliticaIndexRoute
  '/casos': typeof CasosIndexRoute
  '/recepcion': typeof RecepcionIndexRoute
  '/reportes': typeof ReportesIndexRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/reportes/revision': typeof ReportesRevisionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/analitica/': typeof AnaliticaIndexRoute
  '/casos/': typeof CasosIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/reportes/revision/': typeof ReportesRevisionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/recepcion/llamadas'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/analitica/'
    | '/casos/'
    | '/recepcion/'
    | '/reportes/'
    | '/reportes/revision/$emailIngestionId'
    | '/reportes/revision/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/recepcion/llamadas'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/analitica'
    | '/casos'
    | '/recepcion'
    | '/reportes'
    | '/reportes/revision/$emailIngestionId'
    | '/reportes/revision'
  id:
    | '__root__'
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/recepcion/llamadas'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/analitica/'
    | '/casos/'
    | '/recepcion/'
    | '/reportes/'
    | '/reportes/revision/$emailIngestionId'
    | '/reportes/revision/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCatalogosRoute: typeof AdminCatalogosRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AnaliticaCarga147Route: typeof AnaliticaCarga147Route
  AnaliticaMapaRoute: typeof AnaliticaMapaRoute
  CasosTrackingNumberRoute: typeof CasosTrackingNumberRoute
  CasosNuevoRoute: typeof CasosNuevoRoute
  RecepcionLlamadasRoute: typeof RecepcionLlamadasRoute
  ReportesReportIdRoute: typeof ReportesReportIdRoute
  ReportesNuevoRoute: typeof ReportesNuevoRoute
  AnaliticaIndexRoute: typeof AnaliticaIndexRoute
  CasosIndexRoute: typeof CasosIndexRoute
  RecepcionIndexRoute: typeof RecepcionIndexRoute
  ReportesIndexRoute: typeof ReportesIndexRoute
  ReportesRevisionEmailIngestionIdRoute: typeof ReportesRevisionEmailIngestionIdRoute
  ReportesRevisionIndexRoute: typeof ReportesRevisionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogos': {
      id: '/admin/catalogos'
      path: '/admin/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AdminCatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/': {
      id: '/analitica/'
      path: '/analitica'
      fullPath: '/analitica/'
      preLoaderRoute: typeof AnaliticaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/carga-147': {
      id: '/analitica/carga-147'
      path: '/analitica/carga-147'
      fullPath: '/analitica/carga-147'
      preLoaderRoute: typeof AnaliticaCarga147RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/mapa': {
      id: '/analitica/mapa'
      path: '/analitica/mapa'
      fullPath: '/analitica/mapa'
      preLoaderRoute: typeof AnaliticaMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$trackingNumber': {
      id: '/casos/$trackingNumber'
      path: '/casos/$trackingNumber'
      fullPath: '/casos/$trackingNumber'
      preLoaderRoute: typeof CasosTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/nuevo': {
      id: '/casos/nuevo'
      path: '/casos/nuevo'
      fullPath: '/casos/nuevo'
      preLoaderRoute: typeof CasosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion/': {
      id: '/recepcion/'
      path: '/recepcion'
      fullPath: '/recepcion/'
      preLoaderRoute: typeof RecepcionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion/llamadas': {
      id: '/recepcion/llamadas'
      path: '/recepcion/llamadas'
      fullPath: '/recepcion/llamadas'
      preLoaderRoute: typeof RecepcionLlamadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/': {
      id: '/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ReportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/$reportId': {
      id: '/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/reportes/$reportId'
      preLoaderRoute: typeof ReportesReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/nuevo': {
      id: '/reportes/nuevo'
      path: '/reportes/nuevo'
      fullPath: '/reportes/nuevo'
      preLoaderRoute: typeof ReportesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/revision/': {
      id: '/reportes/revision/'
      path: '/reportes/revision'
      fullPath: '/reportes/revision/'
      preLoaderRoute: typeof ReportesRevisionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/revision/$emailIngestionId': {
      id: '/reportes/revision/$emailIngestionId'
      path: '/reportes/revision/$emailIngestionId'
      fullPath: '/reportes/revision/$emailIngestionId'
      preLoaderRoute: typeof ReportesRevisionEmailIngestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCatalogosRoute: AdminCatalogosRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AnaliticaCarga147Route: AnaliticaCarga147Route,
  AnaliticaMapaRoute: AnaliticaMapaRoute,
  CasosTrackingNumberRoute: CasosTrackingNumberRoute,
  CasosNuevoRoute: CasosNuevoRoute,
  RecepcionLlamadasRoute: RecepcionLlamadasRoute,
  ReportesReportIdRoute: ReportesReportIdRoute,
  ReportesNuevoRoute: ReportesNuevoRoute,
  AnaliticaIndexRoute: AnaliticaIndexRoute,
  CasosIndexRoute: CasosIndexRoute,
  RecepcionIndexRoute: RecepcionIndexRoute,
  ReportesIndexRoute: ReportesIndexRoute,
  ReportesRevisionEmailIngestionIdRoute: ReportesRevisionEmailIngestionIdRoute,
  ReportesRevisionIndexRoute: ReportesRevisionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
