/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminCatalogosRouteImport } from './routes/admin/catalogos'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AnaliticaIndexRouteImport } from './routes/analitica/index'
import { Route as AnaliticaCarga147RouteImport } from './routes/analitica/carga-147'
import { Route as AnaliticaMapaRouteImport } from './routes/analitica/mapa'
import { Route as CampoIndexRouteImport } from './routes/campo/index'
import { Route as CampoTrackingNumberRouteImport } from './routes/campo/$trackingNumber'
import { Route as CasosIndexRouteImport } from './routes/casos/index'
import { Route as CasosTrackingNumberRouteImport } from './routes/casos/$trackingNumber'
import { Route as CasosNuevoRouteImport } from './routes/casos/nuevo'
import { Route as FlotaIndexRouteImport } from './routes/flota/index'
import { Route as ObservatorioCargueRouteImport } from './routes/observatorio/cargue'
import { Route as ObservatorioHechosRouteImport } from './routes/observatorio/hechos'
import { Route as RecepcionIndexRouteImport } from './routes/recepcion/index'
import { Route as RecepcionLlamadasRouteImport } from './routes/recepcion/llamadas'
import { Route as RecursosEquiposRouteImport } from './routes/recursos/equipos'
import { Route as ReportesIndexRouteImport } from './routes/reportes/index'
import { Route as ReportesReportIdRouteImport } from './routes/reportes/$reportId'
import { Route as ReportesNuevoRouteImport } from './routes/reportes/nuevo'
import { Route as TablerosIndexRouteImport } from './routes/tableros/index'
import { Route as TablerosBoletinRouteImport } from './routes/tableros/boletin'
import { Route as RecursosFlotaIndexRouteImport } from './routes/recursos/flota/index'
import { Route as RecursosFlotaVehicleIdRouteImport } from './routes/recursos/flota/$vehicleId'
import { Route as ReportesRevisionIndexRouteImport } from './routes/reportes/revision/index'
import { Route as ReportesRevisionEmailIngestionIdRouteImport } from './routes/reportes/revision/$emailIngestionId'
import { Route as TablerosExtorsionIndexRouteImport } from './routes/tableros/extorsion.index'
import { Route as TablerosExtorsionDepartmentRouteImport } from './routes/tableros/extorsion.$department'
import { Route as TablerosSecuestroIndexRouteImport } from './routes/tableros/secuestro.index'
import { Route as TablerosSecuestroDepartmentRouteImport } from './routes/tableros/secuestro.$department'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogosRoute = AdminCatalogosRouteImport.update({
  id: '/admin/catalogos',
  path: '/admin/catalogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaIndexRoute = AnaliticaIndexRouteImport.update({
  id: '/analitica/',
  path: '/analitica/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaCarga147Route = AnaliticaCarga147RouteImport.update({
  id: '/analitica/carga-147',
  path: '/analitica/carga-147',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliticaMapaRoute = AnaliticaMapaRouteImport.update({
  id: '/analitica/mapa',
  path: '/analitica/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoIndexRoute = CampoIndexRouteImport.update({
  id: '/campo/',
  path: '/campo/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoTrackingNumberRoute = CampoTrackingNumberRouteImport.update({
  id: '/campo/$trackingNumber',
  path: '/campo/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosIndexRoute = CasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosTrackingNumberRoute = CasosTrackingNumberRouteImport.update({
  id: '/casos/$trackingNumber',
  path: '/casos/$trackingNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosNuevoRoute = CasosNuevoRouteImport.update({
  id: '/casos/nuevo',
  path: '/casos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const FlotaIndexRoute = FlotaIndexRouteImport.update({
  id: '/flota/',
  path: '/flota/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatorioCargueRoute = ObservatorioCargueRouteImport.update({
  id: '/observatorio/cargue',
  path: '/observatorio/cargue',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatorioHechosRoute = ObservatorioHechosRouteImport.update({
  id: '/observatorio/hechos',
  path: '/observatorio/hechos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionIndexRoute = RecepcionIndexRouteImport.update({
  id: '/recepcion/',
  path: '/recepcion/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecepcionLlamadasRoute = RecepcionLlamadasRouteImport.update({
  id: '/recepcion/llamadas',
  path: '/recepcion/llamadas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosEquiposRoute = RecursosEquiposRouteImport.update({
  id: '/recursos/equipos',
  path: '/recursos/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesIndexRoute = ReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesReportIdRoute = ReportesReportIdRouteImport.update({
  id: '/reportes/$reportId',
  path: '/reportes/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesNuevoRoute = ReportesNuevoRouteImport.update({
  id: '/reportes/nuevo',
  path: '/reportes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const TablerosIndexRoute = TablerosIndexRouteImport.update({
  id: '/tableros/',
  path: '/tableros/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablerosBoletinRoute = TablerosBoletinRouteImport.update({
  id: '/tableros/boletin',
  path: '/tableros/boletin',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosFlotaIndexRoute = RecursosFlotaIndexRouteImport.update({
  id: '/recursos/flota/',
  path: '/recursos/flota/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosFlotaVehicleIdRoute = RecursosFlotaVehicleIdRouteImport.update({
  id: '/recursos/flota/$vehicleId',
  path: '/recursos/flota/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRevisionIndexRoute = ReportesRevisionIndexRouteImport.update({
  id: '/reportes/revision/',
  path: '/reportes/revision/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRevisionEmailIngestionIdRoute =
  ReportesRevisionEmailIngestionIdRouteImport.update({
    id: '/reportes/revision/$emailIngestionId',
    path: '/reportes/revision/$emailIngestionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TablerosExtorsionIndexRoute = TablerosExtorsionIndexRouteImport.update({
  id: '/tableros/extorsion/',
  path: '/tableros/extorsion/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablerosExtorsionDepartmentRoute =
  TablerosExtorsionDepartmentRouteImport.update({
    id: '/tableros/extorsion/$department',
    path: '/tableros/extorsion/$department',
    getParentRoute: () => rootRouteImport,
  } as any)
const TablerosSecuestroIndexRoute = TablerosSecuestroIndexRouteImport.update({
  id: '/tableros/secuestro/',
  path: '/tableros/secuestro/',
  getParentRoute: () => rootRouteImport,
} as any)
const TablerosSecuestroDepartmentRoute =
  TablerosSecuestroDepartmentRouteImport.update({
    id: '/tableros/secuestro/$department',
    path: '/tableros/secuestro/$department',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/campo/$trackingNumber': typeof CampoTrackingNumberRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/observatorio/cargue': typeof ObservatorioCargueRoute
  '/observatorio/hechos': typeof ObservatorioHechosRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/recursos/equipos': typeof RecursosEquiposRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/tableros/boletin': typeof TablerosBoletinRoute
  '/analitica/': typeof AnaliticaIndexRoute
  '/campo/': typeof CampoIndexRoute
  '/casos/': typeof CasosIndexRoute
  '/flota/': typeof FlotaIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/tableros/': typeof TablerosIndexRoute
  '/recursos/flota/$vehicleId': typeof RecursosFlotaVehicleIdRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/tableros/extorsion/$department': typeof TablerosExtorsionDepartmentRoute
  '/tableros/secuestro/$department': typeof TablerosSecuestroDepartmentRoute
  '/recursos/flota/': typeof RecursosFlotaIndexRoute
  '/reportes/revision/': typeof ReportesRevisionIndexRoute
  '/tableros/extorsion/': typeof TablerosExtorsionIndexRoute
  '/tableros/secuestro/': typeof TablerosSecuestroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/campo/$trackingNumber': typeof CampoTrackingNumberRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/observatorio/cargue': typeof ObservatorioCargueRoute
  '/observatorio/hechos': typeof ObservatorioHechosRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/recursos/equipos': typeof RecursosEquiposRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/tableros/boletin': typeof TablerosBoletinRoute
  '/analitica': typeof AnaliticaIndexRoute
  '/campo': typeof CampoIndexRoute
  '/casos': typeof CasosIndexRoute
  '/flota': typeof FlotaIndexRoute
  '/recepcion': typeof RecepcionIndexRoute
  '/reportes': typeof ReportesIndexRoute
  '/tableros': typeof TablerosIndexRoute
  '/recursos/flota/$vehicleId': typeof RecursosFlotaVehicleIdRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/tableros/extorsion/$department': typeof TablerosExtorsionDepartmentRoute
  '/tableros/secuestro/$department': typeof TablerosSecuestroDepartmentRoute
  '/recursos/flota': typeof RecursosFlotaIndexRoute
  '/reportes/revision': typeof ReportesRevisionIndexRoute
  '/tableros/extorsion': typeof TablerosExtorsionIndexRoute
  '/tableros/secuestro': typeof TablerosSecuestroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/analitica/carga-147': typeof AnaliticaCarga147Route
  '/analitica/mapa': typeof AnaliticaMapaRoute
  '/campo/$trackingNumber': typeof CampoTrackingNumberRoute
  '/casos/$trackingNumber': typeof CasosTrackingNumberRoute
  '/casos/nuevo': typeof CasosNuevoRoute
  '/observatorio/cargue': typeof ObservatorioCargueRoute
  '/observatorio/hechos': typeof ObservatorioHechosRoute
  '/recepcion/llamadas': typeof RecepcionLlamadasRoute
  '/recursos/equipos': typeof RecursosEquiposRoute
  '/reportes/$reportId': typeof ReportesReportIdRoute
  '/reportes/nuevo': typeof ReportesNuevoRoute
  '/tableros/boletin': typeof TablerosBoletinRoute
  '/analitica/': typeof AnaliticaIndexRoute
  '/campo/': typeof CampoIndexRoute
  '/casos/': typeof CasosIndexRoute
  '/flota/': typeof FlotaIndexRoute
  '/recepcion/': typeof RecepcionIndexRoute
  '/reportes/': typeof ReportesIndexRoute
  '/tableros/': typeof TablerosIndexRoute
  '/recursos/flota/$vehicleId': typeof RecursosFlotaVehicleIdRoute
  '/reportes/revision/$emailIngestionId': typeof ReportesRevisionEmailIngestionIdRoute
  '/tableros/extorsion/$department': typeof TablerosExtorsionDepartmentRoute
  '/tableros/secuestro/$department': typeof TablerosSecuestroDepartmentRoute
  '/recursos/flota/': typeof RecursosFlotaIndexRoute
  '/reportes/revision/': typeof ReportesRevisionIndexRoute
  '/tableros/extorsion/': typeof TablerosExtorsionIndexRoute
  '/tableros/secuestro/': typeof TablerosSecuestroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/campo/$trackingNumber'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/observatorio/cargue'
    | '/observatorio/hechos'
    | '/recepcion/llamadas'
    | '/recursos/equipos'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/tableros/boletin'
    | '/analitica/'
    | '/campo/'
    | '/casos/'
    | '/flota/'
    | '/recepcion/'
    | '/reportes/'
    | '/tableros/'
    | '/recursos/flota/$vehicleId'
    | '/reportes/revision/$emailIngestionId'
    | '/tableros/extorsion/$department'
    | '/tableros/secuestro/$department'
    | '/recursos/flota/'
    | '/reportes/revision/'
    | '/tableros/extorsion/'
    | '/tableros/secuestro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/campo/$trackingNumber'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/observatorio/cargue'
    | '/observatorio/hechos'
    | '/recepcion/llamadas'
    | '/recursos/equipos'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/tableros/boletin'
    | '/analitica'
    | '/campo'
    | '/casos'
    | '/flota'
    | '/recepcion'
    | '/reportes'
    | '/tableros'
    | '/recursos/flota/$vehicleId'
    | '/reportes/revision/$emailIngestionId'
    | '/tableros/extorsion/$department'
    | '/tableros/secuestro/$department'
    | '/recursos/flota'
    | '/reportes/revision'
    | '/tableros/extorsion'
    | '/tableros/secuestro'
  id:
    | '__root__'
    | '/'
    | '/admin/auditoria'
    | '/admin/catalogos'
    | '/admin/roles'
    | '/admin/usuarios'
    | '/analitica/carga-147'
    | '/analitica/mapa'
    | '/campo/$trackingNumber'
    | '/casos/$trackingNumber'
    | '/casos/nuevo'
    | '/observatorio/cargue'
    | '/observatorio/hechos'
    | '/recepcion/llamadas'
    | '/recursos/equipos'
    | '/reportes/$reportId'
    | '/reportes/nuevo'
    | '/tableros/boletin'
    | '/analitica/'
    | '/campo/'
    | '/casos/'
    | '/flota/'
    | '/recepcion/'
    | '/reportes/'
    | '/tableros/'
    | '/recursos/flota/$vehicleId'
    | '/reportes/revision/$emailIngestionId'
    | '/tableros/extorsion/$department'
    | '/tableros/secuestro/$department'
    | '/recursos/flota/'
    | '/reportes/revision/'
    | '/tableros/extorsion/'
    | '/tableros/secuestro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminCatalogosRoute: typeof AdminCatalogosRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AnaliticaCarga147Route: typeof AnaliticaCarga147Route
  AnaliticaMapaRoute: typeof AnaliticaMapaRoute
  CampoTrackingNumberRoute: typeof CampoTrackingNumberRoute
  CasosTrackingNumberRoute: typeof CasosTrackingNumberRoute
  CasosNuevoRoute: typeof CasosNuevoRoute
  ObservatorioCargueRoute: typeof ObservatorioCargueRoute
  ObservatorioHechosRoute: typeof ObservatorioHechosRoute
  RecepcionLlamadasRoute: typeof RecepcionLlamadasRoute
  RecursosEquiposRoute: typeof RecursosEquiposRoute
  ReportesReportIdRoute: typeof ReportesReportIdRoute
  ReportesNuevoRoute: typeof ReportesNuevoRoute
  TablerosBoletinRoute: typeof TablerosBoletinRoute
  AnaliticaIndexRoute: typeof AnaliticaIndexRoute
  CampoIndexRoute: typeof CampoIndexRoute
  CasosIndexRoute: typeof CasosIndexRoute
  FlotaIndexRoute: typeof FlotaIndexRoute
  RecepcionIndexRoute: typeof RecepcionIndexRoute
  ReportesIndexRoute: typeof ReportesIndexRoute
  TablerosIndexRoute: typeof TablerosIndexRoute
  RecursosFlotaVehicleIdRoute: typeof RecursosFlotaVehicleIdRoute
  ReportesRevisionEmailIngestionIdRoute: typeof ReportesRevisionEmailIngestionIdRoute
  TablerosExtorsionDepartmentRoute: typeof TablerosExtorsionDepartmentRoute
  TablerosSecuestroDepartmentRoute: typeof TablerosSecuestroDepartmentRoute
  RecursosFlotaIndexRoute: typeof RecursosFlotaIndexRoute
  ReportesRevisionIndexRoute: typeof ReportesRevisionIndexRoute
  TablerosExtorsionIndexRoute: typeof TablerosExtorsionIndexRoute
  TablerosSecuestroIndexRoute: typeof TablerosSecuestroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogos': {
      id: '/admin/catalogos'
      path: '/admin/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AdminCatalogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/': {
      id: '/analitica/'
      path: '/analitica'
      fullPath: '/analitica/'
      preLoaderRoute: typeof AnaliticaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/carga-147': {
      id: '/analitica/carga-147'
      path: '/analitica/carga-147'
      fullPath: '/analitica/carga-147'
      preLoaderRoute: typeof AnaliticaCarga147RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitica/mapa': {
      id: '/analitica/mapa'
      path: '/analitica/mapa'
      fullPath: '/analitica/mapa'
      preLoaderRoute: typeof AnaliticaMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/': {
      id: '/campo/'
      path: '/campo'
      fullPath: '/campo/'
      preLoaderRoute: typeof CampoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo/$trackingNumber': {
      id: '/campo/$trackingNumber'
      path: '/campo/$trackingNumber'
      fullPath: '/campo/$trackingNumber'
      preLoaderRoute: typeof CampoTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/': {
      id: '/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof CasosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/$trackingNumber': {
      id: '/casos/$trackingNumber'
      path: '/casos/$trackingNumber'
      fullPath: '/casos/$trackingNumber'
      preLoaderRoute: typeof CasosTrackingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos/nuevo': {
      id: '/casos/nuevo'
      path: '/casos/nuevo'
      fullPath: '/casos/nuevo'
      preLoaderRoute: typeof CasosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flota/': {
      id: '/flota/'
      path: '/flota'
      fullPath: '/flota/'
      preLoaderRoute: typeof FlotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatorio/cargue': {
      id: '/observatorio/cargue'
      path: '/observatorio/cargue'
      fullPath: '/observatorio/cargue'
      preLoaderRoute: typeof ObservatorioCargueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatorio/hechos': {
      id: '/observatorio/hechos'
      path: '/observatorio/hechos'
      fullPath: '/observatorio/hechos'
      preLoaderRoute: typeof ObservatorioHechosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion/': {
      id: '/recepcion/'
      path: '/recepcion'
      fullPath: '/recepcion/'
      preLoaderRoute: typeof RecepcionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepcion/llamadas': {
      id: '/recepcion/llamadas'
      path: '/recepcion/llamadas'
      fullPath: '/recepcion/llamadas'
      preLoaderRoute: typeof RecepcionLlamadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/equipos': {
      id: '/recursos/equipos'
      path: '/recursos/equipos'
      fullPath: '/recursos/equipos'
      preLoaderRoute: typeof RecursosEquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/': {
      id: '/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ReportesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/$reportId': {
      id: '/reportes/$reportId'
      path: '/reportes/$reportId'
      fullPath: '/reportes/$reportId'
      preLoaderRoute: typeof ReportesReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/nuevo': {
      id: '/reportes/nuevo'
      path: '/reportes/nuevo'
      fullPath: '/reportes/nuevo'
      preLoaderRoute: typeof ReportesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/': {
      id: '/tableros/'
      path: '/tableros'
      fullPath: '/tableros/'
      preLoaderRoute: typeof TablerosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/boletin': {
      id: '/tableros/boletin'
      path: '/tableros/boletin'
      fullPath: '/tableros/boletin'
      preLoaderRoute: typeof TablerosBoletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/flota/': {
      id: '/recursos/flota/'
      path: '/recursos/flota'
      fullPath: '/recursos/flota/'
      preLoaderRoute: typeof RecursosFlotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos/flota/$vehicleId': {
      id: '/recursos/flota/$vehicleId'
      path: '/recursos/flota/$vehicleId'
      fullPath: '/recursos/flota/$vehicleId'
      preLoaderRoute: typeof RecursosFlotaVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/revision/': {
      id: '/reportes/revision/'
      path: '/reportes/revision'
      fullPath: '/reportes/revision/'
      preLoaderRoute: typeof ReportesRevisionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes/revision/$emailIngestionId': {
      id: '/reportes/revision/$emailIngestionId'
      path: '/reportes/revision/$emailIngestionId'
      fullPath: '/reportes/revision/$emailIngestionId'
      preLoaderRoute: typeof ReportesRevisionEmailIngestionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/extorsion/': {
      id: '/tableros/extorsion/'
      path: '/tableros/extorsion'
      fullPath: '/tableros/extorsion/'
      preLoaderRoute: typeof TablerosExtorsionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/extorsion/$department': {
      id: '/tableros/extorsion/$department'
      path: '/tableros/extorsion/$department'
      fullPath: '/tableros/extorsion/$department'
      preLoaderRoute: typeof TablerosExtorsionDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/secuestro/': {
      id: '/tableros/secuestro/'
      path: '/tableros/secuestro'
      fullPath: '/tableros/secuestro/'
      preLoaderRoute: typeof TablerosSecuestroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableros/secuestro/$department': {
      id: '/tableros/secuestro/$department'
      path: '/tableros/secuestro/$department'
      fullPath: '/tableros/secuestro/$department'
      preLoaderRoute: typeof TablerosSecuestroDepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminCatalogosRoute: AdminCatalogosRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AnaliticaCarga147Route: AnaliticaCarga147Route,
  AnaliticaMapaRoute: AnaliticaMapaRoute,
  CampoTrackingNumberRoute: CampoTrackingNumberRoute,
  CasosTrackingNumberRoute: CasosTrackingNumberRoute,
  CasosNuevoRoute: CasosNuevoRoute,
  ObservatorioCargueRoute: ObservatorioCargueRoute,
  ObservatorioHechosRoute: ObservatorioHechosRoute,
  RecepcionLlamadasRoute: RecepcionLlamadasRoute,
  RecursosEquiposRoute: RecursosEquiposRoute,
  ReportesReportIdRoute: ReportesReportIdRoute,
  ReportesNuevoRoute: ReportesNuevoRoute,
  TablerosBoletinRoute: TablerosBoletinRoute,
  AnaliticaIndexRoute: AnaliticaIndexRoute,
  CampoIndexRoute: CampoIndexRoute,
  CasosIndexRoute: CasosIndexRoute,
  FlotaIndexRoute: FlotaIndexRoute,
  RecepcionIndexRoute: RecepcionIndexRoute,
  ReportesIndexRoute: ReportesIndexRoute,
  TablerosIndexRoute: TablerosIndexRoute,
  RecursosFlotaVehicleIdRoute: RecursosFlotaVehicleIdRoute,
  ReportesRevisionEmailIngestionIdRoute: ReportesRevisionEmailIngestionIdRoute,
  TablerosExtorsionDepartmentRoute: TablerosExtorsionDepartmentRoute,
  TablerosSecuestroDepartmentRoute: TablerosSecuestroDepartmentRoute,
  RecursosFlotaIndexRoute: RecursosFlotaIndexRoute,
  ReportesRevisionIndexRoute: ReportesRevisionIndexRoute,
  TablerosExtorsionIndexRoute: TablerosExtorsionIndexRoute,
  TablerosSecuestroIndexRoute: TablerosSecuestroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
